name: basic CI

on: [push]

jobs:
  unit_tests:
    runs-on: ubuntu-latest
    container:
      image: python:3.11.4
    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11
      - name: Install dependencies
        run: |
          pip install poetry
          poetry config virtualenvs.in-project false
          poetry install
      - name: Run tests
        run: |
          poetry run pytest
